Add compact output
davidbarsky/tracing-glog pull request #15
Opened 2023-07-31 18:02 UTC by chriskonstad

Hey!  I've been heavily using tracing recently with both tracing glog and other tracing integrations.

I've been finding the combination somewhat unwieldy because that sweet sweet span context that makes tracing so helpful is making tracing-glog's output unreadable, even on my 4k 32" monitor, it's just too long and there are wayyy too many special characters, especially if I wind up debug printing a rust struct in my message (not even in my context).

I'm pretty sure I'm not alone, because of tracing adoption issues seen on other teams (`with_span_context(false)`).  People are finding the output so verbose that they're disabling it, forgetting they disabled it, and then getting confused when tracing "doesn't work" when they try to add context later.

2023-08-02 14:55 UTC, davidbarsky requested changes

2023-08-02 14:55 UTC, davidbarsky commented on examples/tokio.rs
> +        .fmt_fields(GlogFields::default().compact())
let's maybe make this a separate example? It'd be nice to show both compact and non-compact field formatting.

2023-08-02 14:55 UTC, davidbarsky commented on src/lib.rs
> +    /// the complexity of the output's structure.
(You don't need double spaces!)

```suggestion
    /// If span names are not included, then the fields from all spans are
    /// printed as a single list of fields. This results is a more compact output.
```

2023-08-02 14:55 UTC, davidbarsky commented on src/lib.rs
> +    /// ```
Note that if you're using the gnome terminal, you can copy and paste output with HTML-formatted color codes:

```suggestion
    /// # Example Output
    /// With `with_span_names` set to true:
    /// <pre>
    /// I0731 16:23:45.674465 990039 examples/tokio.rs:38] [parent_task{subtasks: 10, reason: "testing"}, subtask{number: 10}] polling subtask, number: 10
    /// </pre>
    ///
    /// With `with_span_names` set to false:
    /// <pre>
    /// I0731 16:23:45.674465 990039 examples/tokio.rs:38] [subtasks: 10, reason: "testing", number: 10] polling subtask, number: 10
    /// <pre>
```

2023-08-02 14:55 UTC, davidbarsky commented on src/lib.rs
> +    /// Uses formatting options which favor compactness.
```suggestion
    /// Sets the formatter to use compact options.
    ///
    /// Setting `.compat()` will set [`GlogFields::use_whitespace_in_field`]
    /// and [`GlogFields::should_quote_strings`] to false.
```

2023-08-02 14:55 UTC, davidbarsky commented on src/lib.rs
> +    /// This is helpful for reducing line width.
```suggestion
    /// Sets whether or not whitespace is added to printed fields.
    ///
    /// This defaults to `false`.
```

2023-08-02 15:00 UTC, chriskonstad commented on src/lib.rs
> +    /// the complexity of the output's structure.
Ah sorry! Habit...

2023-08-02 15:08 UTC, chriskonstad commented on examples/tokio.rs
> +        .fmt_fields(GlogFields::default().compact())
Sounds good! Created a new `tokio_compact` example

2023-08-02 15:36 UTC, chriskonstad commented
<img width="1128" alt="image" src="https://github.com/davidbarsky/tracing-glog/assets/1539144/7513f224-a490-407d-8da9-64c41109cffd">

Rustdoc preview

2023-08-02 19:13 UTC, jsgf commented
Not, to block this change as such, but I'd ideally like some trait which allows general control of formatting of span context. Eg, to append it to the end of the log line in a KV format: `#some.key="some value" #other.key=123 ...`

2023-08-04 19:10 UTC, davidbarsky approved these changes

2023-08-07 19:33 UTC, merged